repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: pretty-format-json
        args: [--autofix]
    -   id: check-added-large-files

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
