[tool.isort]
profile = "black"

[tool.black]
skip-string-normalization=true
line-length = 80
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
    /(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | __pycache__
  | build
  | dist
  | docs
    )/
  '''
