# Generated by Django 5.0.4 on 2024-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_item_options_item_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="deadline",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
    ]
