name: Check code with black and isort
on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  check_black_isort:
    runs-on: ubuntu-latest
    name: Check code with black and isort

    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python 3.6"
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install black and isort
        run: |
          pip install black==21.6b0 isort~=5.8.0
      - name: Check with black
        run: |
          black --check djhtmx
      - name: Check with isort
        run: |
          isort -c --df djhtmx
