name: Coverage Badge

on:
  push:
    branches: [ main, master ]

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    name: "Generate Coverage Badge"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.7.3"
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: make install

    - name: Install Redis CLI
      run: sudo apt-get update && sudo apt-get install -y redis-tools

    - name: Start Redis
      run: sudo systemctl start redis

    - name: Run tests with coverage
      run: make coverage-xml
      env:
        DJHTMX_REDIS_URL: redis://localhost:6379/0

    - name: Extract coverage percentage
      id: coverage
      run: |
        COVERAGE=$(python -c "
        import xml.etree.ElementTree as ET
        tree = ET.parse('src/tests/coverage.xml')
        root = tree.getroot()
        line_rate = float(root.attrib['line-rate'])
        coverage_percent = int(line_rate * 100)
        print(coverage_percent)
        ")
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: djhtmx-coverage.json
        label: coverage
        message: ${{ steps.coverage.outputs.percentage }}%
        color: ${{ steps.coverage.outputs.percentage >= 90 && 'brightgreen' || steps.coverage.outputs.percentage >= 80 && 'yellow' || 'red' }}