repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: pretty-format-json
        args: [--autofix]
    -   id: check-added-large-files

-   repo: https://github.com/returntocorp/semgrep
    rev: 'v0.72.0'
    hooks:
      - id: semgrep
        # See semgrep.dev/rulesets to select a ruleset and copy its URL
        args: ['--config', './semgrep_rules.yaml', '--error']
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        args: [-L, 'ist,unter,oder,sie']  # codespell spreche kein deutsch
        exclude: json
